export default {
  home: 'Home',
  userPanel: 'UserPanel',
  userProfile: 'UserProfile',
  settings: 'Settings',
  notifications: 'Notifications',
  task: 'Task',
  Comments: 'Comments',
  Requests: 'Requests',
  networkError: 'NetworkError',
  landing: 'Landing',
  login: 'Login',
  singUp: 'SingUp',
  codeInput: 'CodeInput',
  createPass: 'CreatePass',
  TABS: {
    add: 'Add',
    myTasks: 'MyTasks',
    more: 'More',
    tasks: 'Tasks',
    recommendation: 'Recommendation',
  },
};
