const text = {
  en: {
    login: 'Login',
    SingUp: 'Sing Up',
    accountExist: 'Already have an account?',
    send: 'Send',
    edit: 'Edit',
    more: 'More',
    save: 'Save',
    add: 'Add',
    less: 'Less',
    image: 'Image',
  },
  ua: {
    login: 'Увійти',
    SingUp: 'Зареєструватися',
    accountExist: 'Вже є аккаунт?',
    send: 'Надіслати',
    edit: 'Редагувати',
    more: 'Більше',
    save: 'Зберегти',
    add: 'Додати',
    less: 'Mенше',
    image: 'Зображення',
  },
  ru: {
    login: 'Войти',
    SingUp: 'Зарегистрироваться',
    accountExist: 'Уже есть аккаунт',
    send: 'Отправить',
    edit: 'Редактировать',
    more: 'Больше',
    save: 'Сохранять',
    add: 'Добавить',
    less: 'Mеньше',
    image: 'Изображение',
  },
};

export default text;
